# EVM space SDK client configurations
eth:
  # Fullnode HTTP endpoint
  url: https://evmrpc-test-us.0g.ai
  # Retry times if failure, if 0 never
  # retry: 0
  # Interval duration before each retry
  # retryInterval: 1s
  # Request timeout duration
  # requestTimeout: 3s
  # Max connections allowed per fullnode
  # maxConnsPerHost: 1024

# Blockchain near head cache configurations
nearHead:
  # Cache size in MB
  cacheSize:
    blocks: 100
    txs: 100
    receipts: 100
    traces: 100
